### ISSUE TITLE
React & Redux Kanban board

### ISSUE THREAD

**Issue by didierganthier** [didierganthier/space-travellers-hub#65]
## What tasks have been done
- [x] Create an empty repository
- [x] Copy the  [template](https://github.com/microverseinc/curriculum-react-redux/projects/1)
- [x] In the card titles you can see categories: Setup, Fetch data, Lists render, Actions, Conditional components, and Filters.
- [x] Assign the tasks
- [x] Open a new issue

## Project Link
- The project can be found [here](https://github.com/didierganthier/space-travellers-hub/projects/2)

## Team Members
- @didierganthier 
- @AlucardSanin 

The Kanban board setup was made by @didierganthier and @AlucardSanin

**Comment by danmainah** [comment]
Hi @didierganthier and @AlucardSanin , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Good design
✔️  Good PR and Description

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
